apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-node-app
  template:
    metadata:
      labels:
        app: docker-node-app
    spec:
      containers:
        - name: docker-node-app
          image: ubuntu:1.0.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          securityContext:
            runAsUser: 1000 
